import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Employee Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex flex-column min-vh-100">

        <Toaster />

        <Navbar /> 

        <main className="container mt-4 flex-grow-1">
          { children }
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
